import type { BeyPart } from './types';

/** Common Beyblade X parts (BX / UX / CX series) — feel free to extend. */
export const PARTS: BeyPart[] = [
  // ---------- BX-series Blades ----------
  { name: 'Dran Buster', series: 'BX', kind: 'blade' },
  { name: 'Dran Sword', series: 'BX', kind: 'blade' },
  { name: 'Dran Dagger', series: 'BX', kind: 'blade' },
  { name: 'Wizard Arrow', series: 'BX', kind: 'blade' },
  { name: 'Wizard Rod', series: 'BX', kind: 'blade' },
  { name: 'Wizard Arrow 2', series: 'BX', kind: 'blade' },
  { name: 'Hells Scythe', series: 'BX', kind: 'blade' },
  { name: 'Hells Chain', series: 'BX', kind: 'blade' },
  { name: 'Hells Hammer', series: 'BX', kind: 'blade' },
  { name: 'Phoenix Wing', series: 'BX', kind: 'blade' },
  { name: 'Phoenix Feather', series: 'BX', kind: 'blade' },
  { name: 'Knight Shield', series: 'BX', kind: 'blade' },
  { name: 'Knight Lance', series: 'BX', kind: 'blade' },
  { name: 'Knight Mail', series: 'BX', kind: 'blade' },
  { name: 'Shark Edge', series: 'BX', kind: 'blade' },
  { name: 'Viper Tail', series: 'BX', kind: 'blade' },
  { name: 'Viper Heli', series: 'BX', kind: 'blade' },
  { name: 'Cobalt Drake', series: 'BX', kind: 'blade' },
  { name: 'Cobalt Saber', series: 'BX', kind: 'blade' },
  { name: 'Cobalt Wolf', series: 'BX', kind: 'blade' },
  { name: 'Rhino Horn', series: 'BX', kind: 'blade' },
  { name: 'Rhino Dagger', series: 'BX', kind: 'blade' },
  { name: 'Keel Shark', series: 'BX', kind: 'blade' },
  { name: 'Shell Killer', series: 'BX', kind: 'blade' },
  { name: 'Unicorn Sting', series: 'BX', kind: 'blade' },
  { name: 'Tusk Mammoth', series: 'BX', kind: 'blade' },
  { name: 'Golem Rock', series: 'BX', kind: 'blade' },
  { name: 'Hippogriff', series: 'BX', kind: 'blade' },
  { name: 'Steel Samurai', series: 'BX', kind: 'blade' },
  { name: 'Whale Wave', series: 'BX', kind: 'blade' },
  { name: 'Wand Wizard', series: 'BX', kind: 'blade' },
  { name: 'Dranzer', series: 'BX', kind: 'blade' },
  { name: 'Inferno Dragoon', series: 'BX', kind: 'blade' },
  { name: 'Gear Spryzen', series: 'BX', kind: 'blade' },
  { name: 'Guilty Longinus', series: 'BX', kind: 'blade' },
  { name: 'Zest Achilles', series: 'BX', kind: 'blade' },
  // ---------- UX-series Blades ----------
  { name: 'Sword Dran', series: 'UX', kind: 'blade' },
  { name: 'Dran Buster 2', series: 'UX', kind: 'blade' },
  { name: 'Crimson Garuda', series: 'UX', kind: 'blade' },
  { name: 'Black Shell', series: 'UX', kind: 'blade' },
  { name: 'Golden Wyvern', series: 'UX', kind: 'blade' },
  { name: 'Grand Edge', series: 'UX', kind: 'blade' },
  { name: 'Eclipse Wizard', series: 'UX', kind: 'blade' },
  { name: 'Shadow Knight', series: 'UX', kind: 'blade' },
  { name: 'Vortex Belial', series: 'UX', kind: 'blade' },
  { name: 'Jade Giacane', series: 'UX', kind: 'blade' },
  { name: 'Storm Temptor', series: 'UX', kind: 'blade' },
  { name: 'Overdrive Phoenix', series: 'UX', kind: 'blade' },
  { name: 'Gear Tyranno', series: 'UX', kind: 'blade' },
  { name: 'Aero Pegasus', series: 'UX', kind: 'blade' },
  { name: 'Hyper Cyclone', series: 'UX', kind: 'blade' },
  { name: 'Magnum Paladin', series: 'UX', kind: 'blade' },
  { name: 'Shining Drakon', series: 'UX', kind: 'blade' },
  { name: 'Storm Storm', series: 'UX', kind: 'blade' },
  { name: 'Galaxy Heart', series: 'UX', kind: 'blade' },
  // ---------- CX-series Blades ----------
  { name: 'Dorgeous Dragon', series: 'CX', kind: 'blade' },
  { name: 'Wyvern Typhoon', series: 'CX', kind: 'blade' },
  { name: 'Incendio Fox', series: 'CX', kind: 'blade' },
  { name: 'Azure Lance', series: 'CX', kind: 'blade' },
  { name: 'Radiant Buster', series: 'CX', kind: 'blade' },
  { name: 'Turbine Sorcerer', series: 'CX', kind: 'blade' },
  { name: 'Phantom Wyvern', series: 'CX', kind: 'blade' },
  { name: 'Kaiser Penguin', series: 'CX', kind: 'blade' },
  { name: 'Golden Emerald', series: 'CX', kind: 'blade' },
  // ---------- Ratchets ----------
  { name: '1-60', series: 'BX', kind: 'ratchet' },
  { name: '1-60A', series: 'BX', kind: 'ratchet' },
  { name: '1-60B', series: 'BX', kind: 'ratchet' },
  { name: '1-60P', series: 'BX', kind: 'ratchet' },
  { name: '2-60', series: 'BX', kind: 'ratchet' },
  { name: '2-60A', series: 'BX', kind: 'ratchet' },
  { name: '2-60B', series: 'BX', kind: 'ratchet' },
  { name: '2-60P', series: 'BX', kind: 'ratchet' },
  { name: '3-60', series: 'BX', kind: 'ratchet' },
  { name: '3-60A', series: 'BX', kind: 'ratchet' },
  { name: '3-60B', series: 'BX', kind: 'ratchet' },
  { name: '3-60P', series: 'BX', kind: 'ratchet' },
  { name: '4-60', series: 'BX', kind: 'ratchet' },
  { name: '4-60A', series: 'BX', kind: 'ratchet' },
  { name: '4-60B', series: 'BX', kind: 'ratchet' },
  { name: '4-60P', series: 'BX', kind: 'ratchet' },
  { name: '5-60', series: 'BX', kind: 'ratchet' },
  { name: '5-60A', series: 'BX', kind: 'ratchet' },
  { name: '5-60B', series: 'BX', kind: 'ratchet' },
  { name: '5-60P', series: 'BX', kind: 'ratchet' },
  { name: '9-60', series: 'BX', kind: 'ratchet' },
  { name: '9-60A', series: 'BX', kind: 'ratchet' },
  { name: '9-60B', series: 'BX', kind: 'ratchet' },
  { name: '9-60P', series: 'BX', kind: 'ratchet' },
  { name: '9-80', series: 'BX', kind: 'ratchet' },
  { name: '9-80A', series: 'BX', kind: 'ratchet' },
  { name: '9-80B', series: 'BX', kind: 'ratchet' },
  { name: '4-70', series: 'UX', kind: 'ratchet' },
  { name: '4-70A', series: 'UX', kind: 'ratchet' },
  { name: '4-70B', series: 'UX', kind: 'ratchet' },
  { name: '7-70', series: 'UX', kind: 'ratchet' },
  { name: '7-70A', series: 'UX', kind: 'ratchet' },
  { name: '7-70B', series: 'UX', kind: 'ratchet' },
  { name: '2-80', series: 'UX', kind: 'ratchet' },
  { name: '2-80A', series: 'UX', kind: 'ratchet' },
  { name: '2-80B', series: 'UX', kind: 'ratchet' },
  { name: '1-70', series: 'CX', kind: 'ratchet' },
  { name: '1-70A', series: 'CX', kind: 'ratchet' },
  { name: '1-70B', series: 'CX', kind: 'ratchet' },
  { name: '3-80', series: 'CX', kind: 'ratchet' },
  { name: '3-80A', series: 'CX', kind: 'ratchet' },
  { name: '3-80B', series: 'CX', kind: 'ratchet' },
  // ---------- Bits ----------
  { name: 'Flat', series: 'BX', kind: 'bit' },
  { name: 'Low Flat', series: 'BX', kind: 'bit' },
  { name: 'High Flat', series: 'BX', kind: 'bit' },
  { name: 'Level', series: 'BX', kind: 'bit' },
  { name: 'Point', series: 'BX', kind: 'bit' },
  { name: 'Ball', series: 'BX', kind: 'bit' },
  { name: 'Orbit', series: 'BX', kind: 'bit' },
  { name: 'Tapered', series: 'BX', kind: 'bit' },
  { name: 'Needle', series: 'BX', kind: 'bit' },
  { name: 'Hexa', series: 'BX', kind: 'bit' },
  { name: 'Gear Flat', series: 'BX', kind: 'bit' },
  { name: 'Gear Ball', series: 'BX', kind: 'bit' },
  { name: 'Gear Point', series: 'BX', kind: 'bit' },
  { name: 'Gear Orbit', series: 'BX', kind: 'bit' },
  { name: 'Gear Needle', series: 'BX', kind: 'bit' },
  { name: 'Gear Hexa', series: 'BX', kind: 'bit' },
  { name: 'Rush', series: 'BX', kind: 'bit' },
  { name: 'Accel', series: 'BX', kind: 'bit' },
  { name: 'Dash', series: 'BX', kind: 'bit' },
  { name: 'Destroy', series: 'BX', kind: 'bit' },
  { name: 'Variable', series: 'BX', kind: 'bit' },
  { name: 'Quattro', series: 'BX', kind: 'bit' },
  { name: 'Elevate', series: 'BX', kind: 'bit' },
  { name: 'Unite', series: 'BX', kind: 'bit' },
  { name: 'Under Needle', series: 'BX', kind: 'bit' },
  { name: 'Flat Al', series: 'BX', kind: 'bit' },
  { name: 'Wing Accel', series: 'BX', kind: 'bit' },
  { name: 'Cyclone', series: 'UX', kind: 'bit' },
  { name: 'Vortex', series: 'UX', kind: 'bit' },
  { name: 'Free Ball', series: 'UX', kind: 'bit' },
  { name: 'Dynamic', series: 'UX', kind: 'bit' },
  { name: 'Spiral', series: 'UX', kind: 'bit' },
  { name: 'Aero', series: 'UX', kind: 'bit' },
  { name: 'Gear Ball 2', series: 'CX', kind: 'bit' },
  { name: 'Gear Flat 2', series: 'CX', kind: 'bit' },
  { name: 'Gear Needle 2', series: 'CX', kind: 'bit' },
  { name: 'Gear Hexa 2', series: 'CX', kind: 'bit' },
];

export function partLabel(p: BeyPart): string {
  return `${p.name} (${p.series})`;
}

export function findParts(query: string, kind: 'blade' | 'ratchet' | 'bit'): BeyPart[] {
  const q = query.trim().toLowerCase();
  if (!q) return PARTS.filter((p) => p.kind === kind).slice(0, 12);
  return PARTS.filter((p) => p.kind === kind && p.name.toLowerCase().includes(q)).slice(0, 12);
}

export function quickNames(kind: 'blade' | 'ratchet' | 'bit'): string[] {
  return PARTS.filter((p) => p.kind === kind).map((p) => p.name);
}